### ISSUE TITLE
Dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by geek80** [Jiasong-Duan/COVID-19-epidemic-trajectories#1]
Hello,Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/4AU6F5

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by Jiasong-Duan** [comment]
Hello,
Yes, I am willing to maintain the dataset. Thanks.
Best,Jiasong
    On Tuesday, June 2, 2020, 02:16:11 PM EDT, geek80 <notifications@github.com> wrote:  
 
 


Hello,Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 dataframe https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/4AU6F5

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by geek80** [comment]
Thanks. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the Dataset creator permissions to your dataset. Then please add relevant metadata - description and keywords to your dataset.

**Comment by Jiasong-Duan** [comment]
Hi! I have created an account in Dataverse. My username is Jiasong.Duan. Please let me know the next steps. Many things past days, so I just registered. Thank you very much.
Best,Jiasong
    On Wednesday, June 3, 2020, 05:27:04 AM EDT, geek80 <notifications@github.com> wrote:  
 
 


Thanks. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the Dataset creator permissions to your dataset. Then please add relevant metadata - description and keywords to your dataset.

**Comment by geek80** [comment]
Hi, You have been given the author permissions for your dataset.  Please add relevant metadata description and keywords and keep the dataset up to date. Thanks.

**Comment by Jiasong-Duan** [comment]
Thank you very much!

    On Wednesday, June 17, 2020, 05:05:41 AM EDT, geek80 <notifications@github.com> wrote:  
 
 


Hi, You have been given the author permissions for your dataset. Please add relevant metadata description and keywords and keep the dataset up to date. Thanks.
